export type IProject = {
    id: string,
    name: string,
    code: string,
    status: number,
    letters: number,
    texts: number,
    lastSubmit: string,
    translatedLetters: number,
    translatedTexts: number,
    approvedLetters: number,
    approvedTexts: number,
    shared: boolean,
    hasSaid: boolean,
    codePage: string,
}